name: azurite deploy single policy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" 

    # clone the azurite github repo
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: NathanKewley/Azurite 
        path: Azurite

    # build and install Azurite into the action container
    - name: Build and Install Azurite
      run: |
        cd Azurite
        pip3 install -r requirements.txt
        python3 -m build
        ls -all
        ls -all /dist
        pip3 install dist/Azurite-0.0.4-py3-none-any.whl
        cd ..

    # Run required Azurite commands
    - name: Deploy
      run: |
        azurite -h
